[package]
name = "local_search_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
log = "0.4.29"
rusqlite = {"version" = "0.38.0", features = ["bundled"]}
llm = "1.3.6"
fastembed = "4.1.0"
anyhow = "1.0.100"

[lib]
name = "local_search_engine"
path = "src/lib.rs"
